version: 2
updates:
  # Atualizar GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "rafaelzanella17"
    assignees:
      - "rafaelzanella17"

  # Atualizar dependências npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "rafaelzanella17"
    assignees:
      - "rafaelzanella17"
    # Agrupar atualizações menores em um único PR
    groups:
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"